### ISSUE TITLE
float128 is not available on windows

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ndstructs#10]
https://github.com/ilastik/ndstructs/blob/c9b0a1c984a5e73505fcee44c3067d880156f63e/ndstructs/utils/JsonSerializable.py#L93

from the [numpy docs](https://numpy.org/doc/stable/user/basics.types.html#extended-precision):
> NumPy does not provide a dtype with more precision than C’s long double; in particular, the 128-bit IEEE quad precision data type (FORTRAN’s REAL*16) is not available.
> np.float96 and np.float128 are provided for users who want specific padding. In spite of the names, np.float96 and np.float128 provide only as much precision as np.longdouble, that is, 80 bits on most x86 machines and 64 bits in standard Windows builds.

On windows `float128` is not available at all. ndstruct 0.3.0dev0 fails on windows for this reason.

**Comment by Tomaz-Vieira** [comment]
You're absolutely right. I had bumped into that, removed it, and then forgot to add it to master -.-

**Comment by Tomaz-Vieira** [comment]
Removed float128 as of 9b3ddf413498b7b6381e04a01b0c4009ce73aaf2
