### ISSUE TITLE
API

### ISSUE THREAD

**Issue by k-dominik** [ilastik/ndstructs#6]
So I had some opportunities now to play around with this package. A lot of it is very nice and convenient to use! However, I also stumbled across some points that we might want to take into account before wider adopting this package. Also I'm adding a `LazyArray5D` (draft: https://github.com/ilastik/ndstructs/pull/5), and thought this is a good opportunity for a discussion.

**`RawShape`**
* Why is `RawShape` needed at all (see note about "convenience" methods like `planes`)? 
* `RawShape` should take `axisorder` string in constructor
* `drop_one_spacial` should be more explicit, maybe take into account axis-ordering

**`Shape`**
* `Slice` and `Array5D` have  `iter_over` methods. I see that it is very logical to have them there. But I would also add it to `Shape` (can use it to generate slices).

**`Array5D`**

* `numpy.asarray` will copy `tuple`s, can use `numpy.array` in order not to confuse.
* have you ever considered sublclassing `numpy.array` removes a lot of special methods? Or keeping at least the data in an ndarray, allowing for forwarding of the special methods.
* `location` is usually called `origin`
* in a related manner, yes, saving `origin` is already nice, however, to be complete one should foresee to keep track of
    * scaling information
    * transformation matrix
* also in a related manner, one would add `image_to_world` and `world_to_image` transformation for easy coordinate translations
* I would drop all convenience methods like `planes`, `iter_over` is more expressive IMO. These methods introduce a new vocabulary. I would always need to check what planes mean in this libs context, as opposed to just iterating over what I want.
* remove debugging leftover
* `__eq__`, could be not feasible for large data.

**`Slice5D`**
* `Slice5D.enlarged` is misleading - `radius` implies a (hyper-)ellipsoid, which in this case can be 5D spanning across time, space and channel.
* add `from_shape5D` method to `Slice5D`
* `rebuild` is only used to call the constructor. Why not make it a classmethod?

what do you think: @Tomaz-Vieira

**Comment by Tomaz-Vieira** [comment]
> **`RawShape`**
> 
>     * Why is `RawShape` needed at all (see note about "convenience" methods like `planes`)?
> 
>     * `RawShape` should take `axisorder` string in constructor
> 
>     * `drop_one_spacial` should be more explicit, maybe take into account axis-ordering

I think I was using it a while ago, but for all the wrong reasons. I think the idea was to be able to call `.raw()` (with no arguments) on `Array5D` (and subclasses), but that led to some dangerous usage which I ended up removing. It's still leftover, but I think it might not be a good idea afterall.

> 
> **`Shape`**
> 
> `Slice` and `Array5D` have  `iter_over` methods. I see that it is very logical to have them there. But I would also add it to `Shape` (can use it to generate slices).

So, the reason `Shape5D` cannot produce slices is because it has no 'anchor', so to speak. A shape of `Shape5D(x=10, y=20)` is valid for any of the following slices, for example: `Slice(x=slice(100,110), slice(200,220))`, `Slice5D(x=slice(3, 13), y=slice(7,27))`, which represent completely different intervals. I was thinking that slices actually define an interval, while shapes are just the extent of such interval, and therefore should not be able to be immediately converted to slices.

Still, it does have a `to_slice5d(offset=Point5D.zero())` method, which at least hints to the fact the slice is supposed to be specified by a point and an offset. And then, with slice in hands, you can iterate over it. I'm open to having the convenience iteration methods, though I don't want us to have too much freedom to shoot ourselves in the foot.
> 
> **`Array5D`**
> 
> `numpy.asarray` will copy `tuple`s, can use `numpy.array` in order not to confuse.

Hmm.. not sure if I follow. What do you mean by "copying tuples" ?

>     * have you ever considered sublclassing `numpy.array` removes a lot of special methods? Or keeping at least the data in an ndarray, allowing for forwarding of the special methods.

I did... In fact, I think that's what Vigra tries to do. Still, I wanted Array5D to NOT allow the same level of freedom that `numpy.array` allows. In particular, I wanted slicing to always be done explicitly with a Slice5D, and prohibit indexing with implicit axis order.

>     * `location` is usually called `origin`
> 
>     * in a related manner, yes, saving `origin` is already nice, however, to be complete one should foresee to keep track of
>       
>       * scaling information
>       * transformation matrix
> 
>     * also in a related manner, one would add `image_to_world` and `world_to_image` transformation for easy coordinate translations

I guess 'position' would be even better than 'origin' for that matter, as it doesn't seem to have any relation with the `0,0,0` point =P

Yeah, it did occur to me to just have a transformation matrix, so that it just encapsulates all translations/rotations/skewings/whatevers, but I'm not sure we should be doing that. I was looking at Array5D as something that represents raw data (or exact pieces of it). If we allow the client to 'sample' the data in any arbitrary way (say, by rotating 30 degrees around z ans scaling y by 1.75), then we'd have to start interpolating points between pixels, and who knows what would be a good, safe, reprodicible way to do that.

It seems to me like we'd be better off leaving the transforms to the rendering code; in fact, we could process our stuff, output it to a 3D texture, and then let the renderer sample that (and interpolate) as it deems appropriate. Not to mention, our data is (i think) stored in a regular orthogonal basis, so we still need to translate crazy viewports into orthogonal tiles, but once that's done, I don't think the Array5D's themslves should really care about what transforms are used to view it.

BUT STILL, I think that the location/origin/position is necessary, because we still need to tile our raw data, since we're expecting to not be able to handle it all at once. Having the position stored in an array5D makes it essentially an independent Tile; it remembers where it came from and you can even use it to merge tiles into a bigger piece if needed, without having to transpose coordinates.

>     * I would drop all convenience methods like `planes`, `iter_over` is more expressive IMO. These methods introduce a new vocabulary. I would always need to check what planes mean in this libs context, as opposed to just iterating over what I want.

Most of those are kind of vigra terminology (at least “scalar image”, “image”, and “volume” are), though I see your point. I don;t mind losing those at all.

>     * remove debugging leftover

Yup, I’ll get on that soon =)

>     * `__eq__`, could be not feasible for large data.

I think the only Array5D child that actually checks for equality pixel/pixel is the one that represents a user scribbling, which I was expecting to be very small. Otherwise, yeah, it doesn’t seem healthy to compare component-wise

> 
> **`Slice5D`**
> 
>     * `Slice5D.enlarged` is misleading - `radius` implies a (hyper-)ellipsoid, which in this case can be 5D spanning across time, space and channel.

Hmm… true. Do you have any suggestions for a name that better implies the (hype)cuboid? (Though I don’t see any problem in allowing space, time and channels to be enlarged)

>     * add `from_shape5D` method to `Slice5D`

I guess it would be consistent, but at least `Slice5D` already has the `shape` property, which kinda does just that.

>     * `rebuild` is only used to call the constructor. Why not make it a classmethod?

So, this was used for the cases in which a method returns a new instance of `self.__class__`. Sometimes just calling `self.__class__(...)` would not be enough, because the child classes would need some extra arguments. So, by calling `rebuild()` instead, the child class has the opportunity to override that method, and pass whatever other parameters its specialized constructor is expecting

**Comment by k-dominik** [comment]
> > **`RawShape`**
> > ```
> > * Why is `RawShape` needed at all (see note about "convenience" methods like `planes`)?
> > 
> > * `RawShape` should take `axisorder` string in constructor
> > 
> > * `drop_one_spacial` should be more explicit, maybe take into account axis-ordering
> > ```
> 
> I think I was using it a while ago, but for all the wrong reasons. I think the idea was to be able to call `.raw()` (with no arguments) on `Array5D` (and subclasses), but that led to some dangerous usage which I ended up removing. It's still leftover, but I think it might not be a good idea afterall.

allright, then let's decide to get rid of that.




> > **`Shape`**
> > `Slice` and `Array5D` have  `iter_over` methods. I see that it is very logical to have them there. But I would also add it to `Shape` (can use it to generate slices).
> 
> So, the reason `Shape5D` cannot produce slices is because it has no 'anchor', so to speak. A shape of `Shape5D(x=10, y=20)` is valid for any of the following slices, for example: `Slice(x=slice(100,110), slice(200,220))`, `Slice5D(x=slice(3, 13), y=slice(7,27))`, which represent completely different intervals. I was thinking that slices actually define an interval, while shapes are just the extent of such interval, and therefore should not be able to be immediately converted to slices.
> 
> Still, it does have a `to_slice5d(offset=Point5D.zero())` method, which at least hints to the fact the slice is supposed to be specified by a point and an offset. And then, with slice in hands, you can iterate over it. I'm open to having the convenience iteration methods, though I don't want us to have too much freedom to shoot ourselves in the foot.

I see this makes sense. Let's keep it that way.



> > **`Array5D`**
> > `numpy.asarray` will copy `tuple`s, can use `numpy.array` in order not to confuse.
> 
> Hmm.. not sure if I follow. What do you mean by "copying tuples" ?

it is just that `numpy.asarray` implies not copying the data, which is not possible with tuples. Since it will always get a tuple `numpy.array` is more expressive.




> > ```
> > * have you ever considered sublclassing `numpy.array` removes a lot of special methods? Or keeping at least the data in an ndarray, allowing for forwarding of the special methods.
> > ```
> 
> I did... In fact, I think that's what Vigra tries to do. Still, I wanted Array5D to NOT allow the same level of freedom that `numpy.array` allows. In particular, I wanted slicing to always be done explicitly with a Slice5D, and prohibit indexing with implicit axis order.

This will be confusing in any case - as some operations are defined, others are not. But true, one would probably expect more numpy-like behavior when subclassing from array.



> > ```
> > * `location` is usually called `origin`
> > 
> > * in a related manner, yes, saving `origin` is already nice, however, to be complete one should foresee to keep track of
> >   
> >   * scaling information
> >   * transformation matrix
> > 
> > * also in a related manner, one would add `image_to_world` and `world_to_image` transformation for easy coordinate translations
> > ```
> 
> 
> I guess 'position' would be even better than 'origin' for that matter, as it doesn't seem to have any relation with the `0,0,0` point =P

it does have a relation with the `0` point. It is the position of the local image coordinate system. E.g. from the itk docs: "The "Origin" is the physical position of the pixel whose "Index" is all zeros". There are other sources that state similar things. If you find a good source to use "position", I'm fine, otherwise I'd prefer to stick to the common vocabulary.


> Yeah, it did occur to me to just have a transformation matrix, so that it just encapsulates all translations/rotations/skewings/whatevers, but I'm not sure we should be doing that. I was looking at Array5D as something that represents raw data (or exact pieces of it). If we allow the client to 'sample' the data in any arbitrary way (say, by rotating 30 degrees around z ans scaling y by 1.75), then we'd have to start interpolating points between pixels, and who knows what would be a good, safe, reprodicible way to do that.
> 
> It seems to me like we'd be better off leaving the transforms to the rendering code; in fact, we could process our stuff, output it to a 3D texture, and then let the renderer sample that (and interpolate) as it deems appropriate. Not to mention, our data is (i think) stored in a regular orthogonal basis, so we still need to translate crazy viewports into orthogonal tiles, but once that's done, I don't think the Array5D's themslves should really care about what transforms are used to view it.
> 
> BUT STILL, I think that the location/origin/position is necessary, because we still need to tile our raw data, since we're expecting to not be able to handle it all at once. Having the position stored in an array5D makes it essentially an independent Tile; it remembers where it came from and you can even use it to merge tiles into a bigger piece if needed, without having to transpose coordinates.

it sounds to me that you don't actually want to save a point, but a slice, for each image. Then it is clear that it refers to something axis aligned. the actual position, in means of world coordinates should be handled elsewhere then.



> > ```
> > * I would drop all convenience methods like `planes`, `iter_over` is more expressive IMO. These methods introduce a new vocabulary. I would always need to check what planes mean in this libs context, as opposed to just iterating over what I want.
> > ```
> 
> 
> Most of those are kind of vigra terminology (at least “scalar image”, “image”, and “volume” are), though I see your point. I don;t mind losing those at all.

to me, usage of these terms seemed necessary in order to use templates. Since we are in python I think we should not copy that stuff.




> > **`RawShape`**
> > ```
> > * Why is `RawShape` needed at all (see note about "convenience" methods like `planes`)?
> > 
> > * `RawShape` should take `axisorder` string in constructor
> > 
> > * `drop_one_spacial` should be more explicit, maybe take into account axis-ordering
> > ```
> 
> I think I was using it a while ago, but for all the wrong reasons. I think the idea was to be able to call `.raw()` (with no arguments) on `Array5D` (and subclasses), but that led to some dangerous usage which I ended up removing. It's still leftover, but I think it might not be a good idea afterall.
> 
> > **`Shape`**
> > `Slice` and `Array5D` have  `iter_over` methods. I see that it is very logical to have them there. But I would also add it to `Shape` (can use it to generate slices).
> 
> So, the reason `Shape5D` cannot produce slices is because it has no 'anchor', so to speak. A shape of `Shape5D(x=10, y=20)` is valid for any of the following slices, for example: `Slice(x=slice(100,110), slice(200,220))`, `Slice5D(x=slice(3, 13), y=slice(7,27))`, which represent completely different intervals. I was thinking that slices actually define an interval, while shapes are just the extent of such interval, and therefore should not be able to be immediately converted to slices.
> 
> Still, it does have a `to_slice5d(offset=Point5D.zero())` method, which at least hints to the fact the slice is supposed to be specified by a point and an offset. And then, with slice in hands, you can iterate over it. I'm open to having the convenience iteration methods, though I don't want us to have too much freedom to shoot ourselves in the foot.
> 
> > **`Array5D`**
> > `numpy.asarray` will copy `tuple`s, can use `numpy.array` in order not to confuse.
> 
> Hmm.. not sure if I follow. What do you mean by "copying tuples" ?
> 
> > ```
> > * have you ever considered sublclassing `numpy.array` removes a lot of special methods? Or keeping at least the data in an ndarray, allowing for forwarding of the special methods.
> > ```
> 
> I did... In fact, I think that's what Vigra tries to do. Still, I wanted Array5D to NOT allow the same level of freedom that `numpy.array` allows. In particular, I wanted slicing to always be done explicitly with a Slice5D, and prohibit indexing with implicit axis order.
> 
> > ```
> > * `location` is usually called `origin`
> > 
> > * in a related manner, yes, saving `origin` is already nice, however, to be complete one should foresee to keep track of
> >   
> >   * scaling information
> >   * transformation matrix
> > 
> > * also in a related manner, one would add `image_to_world` and `world_to_image` transformation for easy coordinate translations
> > ```
> 
> I guess 'position' would be even better than 'origin' for that matter, as it doesn't seem to have any relation with the `0,0,0` point =P
> 
> Yeah, it did occur to me to just have a transformation matrix, so that it just encapsulates all translations/rotations/skewings/whatevers, but I'm not sure we should be doing that. I was looking at Array5D as something that represents raw data (or exact pieces of it). If we allow the client to 'sample' the data in any arbitrary way (say, by rotating 30 degrees around z ans scaling y by 1.75), then we'd have to start interpolating points between pixels, and who knows what would be a good, safe, reprodicible way to do that.
> 
> It seems to me like we'd be better off leaving the transforms to the rendering code; in fact, we could process our stuff, output it to a 3D texture, and then let the renderer sample that (and interpolate) as it deems appropriate. Not to mention, our data is (i think) stored in a regular orthogonal basis, so we still need to translate crazy viewports into orthogonal tiles, but once that's done, I don't think the Array5D's themslves should really care about what transforms are used to view it.
> 
> BUT STILL, I think that the location/origin/position is necessary, because we still need to tile our raw data, since we're expecting to not be able to handle it all at once. Having the position stored in an array5D makes it essentially an independent Tile; it remembers where it came from and you can even use it to merge tiles into a bigger piece if needed, without having to transpose coordinates.
> 
> > ```
> > * I would drop all convenience methods like `planes`, `iter_over` is more expressive IMO. These methods introduce a new vocabulary. I would always need to check what planes mean in this libs context, as opposed to just iterating over what I want.
> > ```
> 
> Most of those are kind of vigra terminology (at least “scalar image”, “image”, and “volume” are), though I see your point. I don;t mind losing those at all.
> 
> > ```
> > * remove debugging leftover
> > ```
> 
> Yup, I’ll get on that soon =)
> 
> > ```
> > * `__eq__`, could be not feasible for large data.
> > ```
> 
> I think the only Array5D child that actually checks for equality pixel/pixel is the one that represents a user scribbling, which I was expecting to be very small. Otherwise, yeah, it doesn’t seem healthy to compare component-wise
> 
> > **`Slice5D`**
> > ```
> > * `Slice5D.enlarged` is misleading - `radius` implies a (hyper-)ellipsoid, which in this case can be 5D spanning across time, space and channel.
> > ```
> 
> Hmm… true. Do you have any suggestions for a name that better implies the (hype)cuboid? (Though I don’t see any problem in allowing space, time and channels to be enlarged)
> 
> > ```
> > * add `from_shape5D` method to `Slice5D`
> > ```
> 
> I guess it would be consistent, but at least `Slice5D` already has the `shape` property, which kinda does just that.
> 
> > ```
> > * `rebuild` is only used to call the constructor. Why not make it a classmethod?
> > ```
> 
> So, this was used for the cases in which a method returns a new instance of `self.__class__`. Sometimes just calling `self.__class__(...)` would not be enough, because the child classes would need some extra arguments. So, by calling `rebuild()` instead, the child class has the opportunity to override that method, and pass whatever other parameters its specialized constructor is expecting

how about calling it `halo`? and the method `add_halo` or something.



> > **`RawShape`**
> > ```
> > * Why is `RawShape` needed at all (see note about "convenience" methods like `planes`)?
> > 
> > * `RawShape` should take `axisorder` string in constructor
> > 
> > * `drop_one_spacial` should be more explicit, maybe take into account axis-ordering
> > ```
> 
> I think I was using it a while ago, but for all the wrong reasons. I think the idea was to be able to call `.raw()` (with no arguments) on `Array5D` (and subclasses), but that led to some dangerous usage which I ended up removing. It's still leftover, but I think it might not be a good idea afterall.
> 
> > **`Shape`**
> > `Slice` and `Array5D` have  `iter_over` methods. I see that it is very logical to have them there. But I would also add it to `Shape` (can use it to generate slices).
> 
> So, the reason `Shape5D` cannot produce slices is because it has no 'anchor', so to speak. A shape of `Shape5D(x=10, y=20)` is valid for any of the following slices, for example: `Slice(x=slice(100,110), slice(200,220))`, `Slice5D(x=slice(3, 13), y=slice(7,27))`, which represent completely different intervals. I was thinking that slices actually define an interval, while shapes are just the extent of such interval, and therefore should not be able to be immediately converted to slices.
> 
> Still, it does have a `to_slice5d(offset=Point5D.zero())` method, which at least hints to the fact the slice is supposed to be specified by a point and an offset. And then, with slice in hands, you can iterate over it. I'm open to having the convenience iteration methods, though I don't want us to have too much freedom to shoot ourselves in the foot.
> 
> > **`Array5D`**
> > `numpy.asarray` will copy `tuple`s, can use `numpy.array` in order not to confuse.
> 
> Hmm.. not sure if I follow. What do you mean by "copying tuples" ?
> 
> > ```
> > * have you ever considered sublclassing `numpy.array` removes a lot of special methods? Or keeping at least the data in an ndarray, allowing for forwarding of the special methods.
> > ```
> 
> I did... In fact, I think that's what Vigra tries to do. Still, I wanted Array5D to NOT allow the same level of freedom that `numpy.array` allows. In particular, I wanted slicing to always be done explicitly with a Slice5D, and prohibit indexing with implicit axis order.
> 
> > ```
> > * `location` is usually called `origin`
> > 
> > * in a related manner, yes, saving `origin` is already nice, however, to be complete one should foresee to keep track of
> >   
> >   * scaling information
> >   * transformation matrix
> > 
> > * also in a related manner, one would add `image_to_world` and `world_to_image` transformation for easy coordinate translations
> > ```
> 
> I guess 'position' would be even better than 'origin' for that matter, as it doesn't seem to have any relation with the `0,0,0` point =P
> 
> Yeah, it did occur to me to just have a transformation matrix, so that it just encapsulates all translations/rotations/skewings/whatevers, but I'm not sure we should be doing that. I was looking at Array5D as something that represents raw data (or exact pieces of it). If we allow the client to 'sample' the data in any arbitrary way (say, by rotating 30 degrees around z ans scaling y by 1.75), then we'd have to start interpolating points between pixels, and who knows what would be a good, safe, reprodicible way to do that.
> 
> It seems to me like we'd be better off leaving the transforms to the rendering code; in fact, we could process our stuff, output it to a 3D texture, and then let the renderer sample that (and interpolate) as it deems appropriate. Not to mention, our data is (i think) stored in a regular orthogonal basis, so we still need to translate crazy viewports into orthogonal tiles, but once that's done, I don't think the Array5D's themslves should really care about what transforms are used to view it.
> 
> BUT STILL, I think that the location/origin/position is necessary, because we still need to tile our raw data, since we're expecting to not be able to handle it all at once. Having the position stored in an array5D makes it essentially an independent Tile; it remembers where it came from and you can even use it to merge tiles into a bigger piece if needed, without having to transpose coordinates.
> 
> > ```
> > * I would drop all convenience methods like `planes`, `iter_over` is more expressive IMO. These methods introduce a new vocabulary. I would always need to check what planes mean in this libs context, as opposed to just iterating over what I want.
> > ```
> 
> Most of those are kind of vigra terminology (at least “scalar image”, “image”, and “volume” are), though I see your point. I don;t mind losing those at all.
> 
> > ```
> > * remove debugging leftover
> > ```
> 
> Yup, I’ll get on that soon =)
> 
> > ```
> > * `__eq__`, could be not feasible for large data.
> > ```
> 
> I think the only Array5D child that actually checks for equality pixel/pixel is the one that represents a user scribbling, which I was expecting to be very small. Otherwise, yeah, it doesn’t seem healthy to compare component-wise
> 
> > **`Slice5D`**
> > ```
> > * `Slice5D.enlarged` is misleading - `radius` implies a (hyper-)ellipsoid, which in this case can be 5D spanning across time, space and channel.
> > ```
> 
> Hmm… true. Do you have any suggestions for a name that better implies the (hype)cuboid? (Though I don’t see any problem in allowing space, time and channels to be enlarged)
> 
> > ```
> > * add `from_shape5D` method to `Slice5D`
> > ```
> 
> I guess it would be consistent, but at least `Slice5D` already has the `shape` property, which kinda does just that.
> 
> > ```
> > * `rebuild` is only used to call the constructor. Why not make it a classmethod?
> > ```
> 
> So, this was used for the cases in which a method returns a new instance of `self.__class__`. Sometimes just calling `self.__class__(...)` would not be enough, because the child classes would need some extra arguments. So, by calling `rebuild()` instead, the child class has the opportunity to override that method, and pass whatever other parameters its specialized constructor is expecting

maybe the name is just misleading. Also it sounds like it should be private, since only the instance seems to be knowing what it can do with it, right?

**Comment by Tomaz-Vieira** [comment]
> it does have a relation with the `0` point. It is the position of the local image coordinate system. E.g. from the itk docs: _"The "Origin" is the physical position of the pixel whose "Index" is all zeros"_. There are other sources that state similar things. If you find a good source to use "position", I'm fine, otherwise I'd prefer to stick to the common vocabulary.

You're right, I guess I should've said that I don't want people to confuse it with the world origin. Well, Unity3D likes ['position'](https://docs.unity3d.com/ScriptReference/Transform-position.html), and so does [Qt](https://doc.qt.io/qt-5/qwidget.html#pos-prop). Blender, on the other hand, likes ['location'](https://docs.blender.org/api/blender_python_api_2_77_0/info_api_reference.html#simple-data-access). So I guess it could be whatever we want =P

> it sounds to me that you don't actually want to save a point, but a slice, for each image. Then it is clear that it refers to something axis aligned. the actual position, in means of world coordinates should be handled elsewhere then.

I'm only saving a point (location/origin/position) rather than a slice because the Array5D already has an implicit shape, which, when combined with it's location/origin/position, produces a Slice5D that represents where that tile fits in the whole image. Saving an actual slice would run us the risk of having location + shape mismatch the slice value.

> to me, usage of these terms seemed particularly interesting to show off some templating stuff. Since we are in python I think we should not copy that stuff.

I kinda liked them, but I can see how they might be obtuse. We can just get rid of them =)

> how about calling it `halo`? and the method `add_halo` or something.

But 'halo' is also a very roundy word, isn't it? ^^ I like the the name `enlarge`, though, or at least something close to it... `expand`, `increase`, `grow`, whatever, as it seems to indicate what is happening to the slice; it's increasing in size. `add_halo` might feel like `halo` is a new, different entity in the library.

> maybe the name [rebuild] is just misleading. Also it sounds like it should be private, since only the instance seems to be knowing what it can do with it, right?

It should be 'protected' =P The parent class is usually the one to call it. What do you think a decent name would be here? `new_self`? `construct` ?

**Comment by Tomaz-Vieira** [comment]
> to me, usage of these terms seemed particularly interesting to show off some templating stuff. Since we are in python I think we should not copy that stuff.

Ah, yeah. I forgot to mention: Having methods like e.g. `planes` or `frames` allow us to return different types, e.g.: FlatArray or StaticArray (an array guaranteed to have `t=1`). I'm not sure I have managed to use those everywhere in the train/predict code, but I liked having those type annotations to know what kinds of data the methods were expecting.

**Comment by k-dominik** [comment]
First of all I think this is totally outdated. Also might be more productive to discuss smaller pieces at a time.
